import UI from './ui';

export const metadata: Metadata = {
  title: 'Minibox Clone',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div>
      <UI />
    </div>
  );
}
